# Generated by Django 3.2.5 on 2021-09-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapplication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=70)),
                ('lastname', models.CharField(max_length=70)),
                ('emailaddress', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='desc',
            field=models.TextField(),
        ),
    ]
