# Generated by Django 3.2.5 on 2021-08-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapplication', '0002_student_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.IntegerField()),
                ('tname', models.CharField(max_length=70)),
                ('temail', models.CharField(max_length=70)),
                ('tpass', models.CharField(max_length=70)),
                ('comments', models.CharField(max_length=10)),
            ],
        ),
    ]
