# Generated by Django 3.2.5 on 2021-09-09 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapplication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_cat',
        ),
    ]
